#!/bin/bash

set -euo pipefail
# set -x

testdir="c-testsuite/tests/single-exec"

max=$(find "$testdir" -name '*.c' | wc -l)

limit="${1:-$max}"
passed="0"
echo "running $limit"

for i in $(seq "$limit")
do
    cfile="$testdir/$(printf "%05d" "$i").c"
    if ! ./run-test "$cfile" &>/dev/null
    then
        echo -ne "\033[0;31mx\033[0m"
    else
        echo -ne "\033[0;32mx\033[0m"
        passed=$(($passed + 1))
    fi

    if [ "$(($i % 25))" == "0" ]
    then
        echo
    elif [ "$(($i % 5))" == "0" ]
    then
        echo -n " "
    fi
done
echo -e "\npassed $passed/$limit"