#!/bin/bash

set -euo pipefail

scratchdir=$(mktemp -d)
cleanup () {
  rm -rf "$scratchdir"
}
trap cleanup EXIT

show() {
    bat --paging=never --map-syntax='*.wat:Lisp' "$@"
}

path="$1"
t=$(basename "$path")
show "$path"

if ! python compiler.py "$path" > "$scratchdir/$t.wat"
then
    show "$scratchdir/$t.wat"
    exit 1
fi

show "$scratchdir/$t.wat"

if ! wasmer run "$scratchdir/$t.wat" -i main > "$scratchdir/$t.out"
then
    exit 1
fi

out=$(cat "$scratchdir/$t.out")
show "$scratchdir/$t.out"

if [[ "$out" != "0" ]]
then
    exit 1
fi